name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adoptopenjdk'

    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Install Gradle 4.0.1
      run: |
        wget https://services.gradle.org/distributions/gradle-4.0.1-bin.zip
        unzip gradle-4.0.1-bin.zip
        sudo mv gradle-4.0.1 /opt/gradle
        sudo ln -s /opt/gradle/bin/gradle /usr/local/bin/gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 28
        build-tools: 28.0.3

    - name: Build Android app with Gradle 4.0.1
      run: gradle assembleRelease
